version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations carsapp && python manage.py migrate carsapp && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
  postgres_data: